I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/cenaCorrida1.rpy", line 131, in script
Exception: Sayer 'JG' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/junior/renpy-6.17.3-sdk/renpy/execution.py", line 294, in run
    node.execute()
  File "/home/junior/renpy-6.17.3-sdk/renpy/ast.py", line 440, in execute
    raise Exception("Sayer '%s' is not defined." % self.who.encode("utf-8"))
Exception: Sayer 'JG' is not defined.

Linux-3.11.0-20-generic-x86_64-with-debian-wheezy-sid
Ren'Py 6.17.3.327
ESofTeacher 0.0
